// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import goresilience "github.com/slok/goresilience"
import mock "github.com/stretchr/testify/mock"

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, f
func (_m *Runner) Run(ctx context.Context, f goresilience.Func) error {
	ret := _m.Called(ctx, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, goresilience.Func) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
