// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: f
func (_m *Executor) Execute(f func() error) error {
	ret := _m.Called(f)

	var r0 error
	if rf, ok := ret.Get(0).(func(func() error) error); ok {
		r0 = rf(f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWorkerQuantity provides a mock function with given fields: quantity
func (_m *Executor) SetWorkerQuantity(quantity int) {
	_m.Called(quantity)
}
